name: Run Batch Transform Job

on:
  workflow_dispatch:  # 👈 can trigger manually
  push:
    branches:
      - main
    paths:
      - cicd/batch_transform.py
      - .github/workflows/batch_transform.yml

jobs:
  batch-transform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install boto3 sagemaker pandas joblib

      - name: Run Batch Transform
        run: python cicd/batch_transform.py
