# .github/workflows/preprocess.yml

name: Rossmann Preprocessing Job

on:
  push:
    branches:
      - main
    paths:
      - scripts/preprocess.py
      - cicd/run_preprocessing_job.py
      - .github/workflows/preprocess.yml

jobs:
  preprocess:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          pip install boto3 sagemaker pandas scikit-learn joblib

      - name: Run SageMaker Preprocessing Job
        run: python cicd/run_preprocessing_job.py
